# Generated by Django 3.2 on 2022-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='workout_type_name',
            field=models.CharField(max_length=100),
        ),
    ]
