# Generated by Django 3.2 on 2022-03-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_daytime',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutDayTime',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
